version: '3.4'

services:
  taskmanagerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;https://+:8081;
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CertificatePassword}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
      - ConnectionStrings__AuthenticationDbConnection=${ConnectionStrings__AuthenticationDbConnection}
      - ConnectionStrings__TaskManagerDbConnection=${ConnectionStrings__TaskManagerDbConnection}
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AuthSettings__RefreshExpiryInDays=${AuthSettings__RefreshExpiryInDays}
      - AllowedCORSOrigins=${AllowedCORSOrigins}
      - Logging__LogLevel__Default=Information
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro