name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/TaskManager.Backend/**'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api:
          - name: "Task Manager Api"
            path: "TaskManagerApi"
            azure_app_name: "taskmanager-api-germanywestcentral-001"
            publish_secret: API_PUBLISH_SECRET
        test:
          - name: "Authentication Tests"
            project_path: "test/TaskManager.Backend/AuthenticationTests/AuthenticationTests.csproj"
          - name: "Shared Tests"
            project_path: "test/TaskManager.Backend/SharedTests/SharedTests.csproj"
          - name: "Metalama Tests"
            project_path: "test/TaskManager.Backend/MetalamaTests/MetalamaTests.csproj"
          - name: "Task Manager Api Tests"
            project_path: "test/TaskManager.Backend/TaskManagerApiTests/TaskManagerApiTests.csproj"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: |
          src/TaskManager.Backend/**/bin
          src/TaskManager.Backend/**/obj
          test/TaskManager.Backend/**/bin
          test/TaskManager.Backend/**/obj
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/*.cs') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ hashFiles('**/*.csproj') }}

    - name: Restore dependencies
      run: dotnet restore src/TaskManager.Backend/${{ matrix.api.path }}/${{ matrix.api.path }}.csproj

    - name: Build project
      run: dotnet build src/TaskManager.Backend/${{ matrix.api.path }}/${{ matrix.api.path }}.csproj --configuration Release

    - name: Run unit tests - ${{ matrix.test.name }}
      run: dotnet test ${{ matrix.test.project_path }} --verbosity normal --configuration Release

    - name: Publish
      run: dotnet publish src/TaskManager.Backend/${{ matrix.api.path }} --configuration Release --output ./src/TaskManager.Backend/${{ matrix.api.path }}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ matrix.api.azure_app_name }}
        slot-name: 'production'
        publish-profile: ${{ secrets[matrix.api.publish_secret] }}
        package: ./src/TaskManager.Backend/${{ matrix.api.path }}/publish